run:
  timeout: 5m
  allow-parallel-runners: true
linters-settings:
  depguard:
    rules:
      forbid-sort-pkg:
        deny:
          - pkg: sort
            desc: Should be replaced with slices package
  revive:
    rules:
      - name: comment-spacings
      - name: import-shadowing
linters:
  disable-all: true
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - modernize
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
issues:
  exclude-generated: lax
  exclude-rules:
    - linters:
        - lll
      path: api/*
    - linters:
        - dupl
        - lll
      path: internal/*
  exclude-dirs:
    - third_party$
    - builtin$
    - examples$
