controller:
  image:
    repository: ghcr.io/ezzops/idle-scale-controller
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1

agent:
  image:
    repository: ghcr.io/ezzops/idle-scale-agent
    tag: latest
    pullPolicy: IfNotPresent

rbac:
  create: true

serviceAccount:
  controller: idle-scale-controller
  agent: idle-scale-agent
