apiVersion: v1
entries:
  idle-scale:
  - apiVersion: v2
    appVersion: 0.1.0-rc1
    created: "2026-07-27T09:48:54.028566313Z"
    description: Idle Scale — scale Deployments to zero and wake on traffic via sentinel
      pods
    digest: c7c37dd2bc5760cc7db28fc0702342d602e07c007ff58327be5dda2c9aba3966
    home: https://github.com/EzzOps/idle-scale
    keywords:
    - kubernetes
    - idle
    - scale-to-zero
    - autoscaling
    maintainers:
    - name: EzzOps
      url: https://github.com/EzzOps
    name: idle-scale
    sources:
    - https://github.com/EzzOps/idle-scale
    type: application
    urls:
    - https://ezzops.github.io/idle-scale/charts/idle-scale-0.1.0-rc1.tgz
    version: 0.1.0-rc1
generated: "2026-07-27T09:48:54.024295783Z"
