apiVersion: v1
entries:
  idle-scale:
  - apiVersion: v2
    appVersion: 0.1.0-rc1
    created: "2026-07-27T10:44:20.547608023Z"
    description: Idle Scale — scale Deployments to zero and wake on traffic via sentinel
      pods
    digest: b6ae5dec21d7fd402774e788df0e0d5a1a86023ec5bacdb3220273fbf27777dc
    home: https://github.com/EzzOps/idle-scale
    keywords:
    - kubernetes
    - idle
    - scale-to-zero
    - autoscaling
    maintainers:
    - name: EzzOps
      url: https://github.com/EzzOps
    name: idle-scale
    sources:
    - https://github.com/EzzOps/idle-scale
    type: application
    urls:
    - https://ezzops.github.io/idle-scale/charts/idle-scale-0.1.0-rc1.tgz
    version: 0.1.0-rc1
generated: "2026-07-27T10:44:20.547309431Z"
