apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "idle-scale.controllerName" . }}
  namespace: idle-scale-system
  labels:
    {{- include "idle-scale.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: idle-scale
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: idle-scale
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: controller
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          env:
            - name: SENTINEL_IMAGE
              value: "{{ .Values.sentinel.image.repository }}:{{ .Values.sentinel.image.tag }}"
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
